import React, { useState, useEffect } from 'react';
import {prefixdata, middledata, suffixdata} from './dataset2';
import './App.css';

function Comparison() {

  // Random Number Generators
    const aBigRandomNumber = Math.floor(Math.random() * 5160) + 1
    const randomNumberPrefix = Math.floor(Math.random() * 40) + 1
    const randomNumberMiddle = Math.floor(Math.random() * 32) + 1
    const randomNumberSuffix = Math.floor(Math.random() * 57) + 1

  // Use State
    const [realName, setRealName] = useState();
    const [fakeName, setFakeName] = useState();

  // API Call
    const makeAPICall = () => (
      fetch("https://rxnav.nlm.nih.gov/REST/allconcepts.json?tty=BN")
      .then((response) => response.json())
      .then((results) => setRealName(results.minConceptGroup.minConcept[aBigRandomNumber].name)) )

  // Use Effect
    useEffect(() => {
      makeAPICall();
      }, [])

  // Handle Click
  const handleComparison = () => {
    setFakeName(prefixdata[randomNumberPrefix] + middledata[randomNumberMiddle] + suffixdata[randomNumberSuffix]);
    makeAPICall(realName);
  }

  return (
    <div className="comparison">
        {/* Instructions */}
      <h3>Drug Name Comparison</h3>
      <p>Let's see how Medipram's names compare to current prescription drug names on the market.</p>
      <h4>You decide. Which name is a real product and which is a name generated by Medipram?</h4>

            {/* Real Drug */}
        <p>{realName ? realName : 'Loading...'}</p> 

        <p>vs.</p>

            {/* Fake Drug */}
        <p>{fakeName ? fakeName : 'Venpradone'}</p>

        <button onClick={() => {handleComparison()}}>Generate a Comparison</button>
    </div>
  );
}

export default Comparison;

